# FROM mcr.microsoft.com/playwright:v1.49.1-noble
# RUN apt-get update && apt-get install -y ffmpeg

# docker build -t playwright-with-ffmpeg


# FROM mcr.microsoft.com/playwright:v1.49.1-noble

# # Install ffmpeg
# RUN apt-get update && apt-get install -y ffmpeg

# # Build the Docker image
# docker build -t playwright-with-ffmpeg .


FROM mcr.microsoft.com/playwright:v1.49.1-noble

# Install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Build the Docker image
docker build -t playwright-with-ffmpeg .
